name: Norminette

on:
  push:
    branches:
      - main

jobs:
  check-norminette:
    name: Norminette
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'sdevsantiago/42_project_template' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Norminette
        run: pip install --upgrade norminette

      - name: Show Version
        run: norminette --version

      - name: Run Norminette
        run: norminette --use-gitignore > norminette-report.txt; grep "Error" norminette-report.txt; if [ $? -eq 1 ]; then exit 0; else exit 1; fi

      - name: Upload Norminette report
        uses: actions/upload-artifact@v4
        with:
          name: norminette-report
          path: norminette-report.txt
